# Minikube Variables
KUBERNETES_VERSION = ENV['KUBERNETES_VERSION'] || "1.20.0"

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.provider "hyperv"
    config.vm.network "public_network"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "hyperv" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
        vb.vmname = "minikube01"
        vb.enable_virtualization_extensions = true
        vb.linked_clone = true
    end
    config.vm.provision :shell, path: "docker.sh", privileged: false
    config.vm.provision :shell, path: "bootstrap.sh", privileged: false
    config.vm.provision :shell, path: "minikubescript.sh", privileged: false
end