-
  name: Deploy prerequisites 
  hosts: web1, db1
  tasks:
    - 
      name: install python3
      dnf:
        name: python3
        state: present
      become: yes
    -
      name: install firewalld
      dnf:
        name: firewalld
        state: present
      become: yes
    -
      name: start firewalld
      service: 
        name: firewalld
        state: started
        enabled: yes
      become: yes
-
  name: Deploy and configure database
  hosts: db1
  tasks:
    -
      name: install mariadb-server
      dnf:
        name: mariadb-server
        state: present
      become: yes
    -
      name: start mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes
      become: yes
    - 
      name: configure firewall for database
      firewalld:
        port: 3306/tcp
        permanent: yes
        immediate: yes
        zone: public
        state: enabled
      become: yes
    -
      name: pip install PyMySQL module
      pip:
        name: PyMySQL
      become: yes
    - 
      name: Create a new database with name 'ecomdb'
      mysql_db:
        name: ecomdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: db_created
      become: yes
    - 
      name: Create database user with name 'ecomuser' and password 'ecompassword' with all database privileges
      mysql_user:
        name: ecomuser
        password: ecompassword
        host: 172.31.96.229
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      become: yes
    - 
      name: copy DB dump file
      copy:
        src: db-load-script.sql
        dest: /tmp
    - 
      name: populate all DBs from SQL file
      mysql_db:
        name: all
        state: import
        target: /tmp/db-load-script.sql
      when: db_created.changed
- 
  name: Deploy and configure web
  hosts: web1
  tasks: 
  - 
    name: Install prerequisites
    dnf:
      name: 
        - httpd
        - php
        - php 
        - php-cli 
        - php-php-gettext 
        - php-mbstring 
        - php-mcrypt 
        - php-mysqlnd 
        - php-pear 
        - php-curl 
        - php-gd 
        - php-xml 
        - php-bcmath 
        - php-zip
        - git
      state: present
    become: yes
  - 
    name: configure firewall 
    firewalld:
      port: 80/tcp
      permanent: yes
      immediate: yes
      zone: public
      state: enabled
    become: yes
  - 
    name: configure httpd
    replace: 
      path: /etc/httpd/conf/httpd.conf
      regexp: "DirectoryIndex index.html"
      replace: "DirectoryIndex index.php"
    become: yes
  -
    name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes
    become: yes
  -
    name: download website from git
    git:
      repo: git clone https://github.com/kodekloudhub/learning-app-ecommerce.git 
      dest: /var/www/html/
      clone: yes
      update: no
    become: yes
  -
    name: update database in index.php
    replace:
      path: /var/www/html/index.php
      regexp: "172.20.1.101"
      replace: "173.31.101.211"
    become: yes